server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:psychological_evaluations}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}

  webflux:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  webjars:
    prefix: /webjars

logging:
  level:
    pe.edu.vallegrande: DEBUG
    org.springframework.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
