apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: vidal  # Se cambia al namespace creado
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLWx1Y2t5LW1vcm5pbmctYWN2NzNpeXAtcG9vbGVyLnNhLWVhc3QtMS5hd3MubmVvbi50ZWNoOjU0MzIvcHN5Y2hvbG9neT9zc2xtb2RlPXJlcXVpcmU=
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX2tNMElDYVQxeWRBbA==

# Comandos para convertir a Base64 y decodificar | https://www.convertstring.com/es/EncodeDecode/Base64Encode

# echo -n "demo123" | base64

# echo "ZGVtbzEyMw==" | base64 --decode
