# kubectl apply -f 3-service.yml
apiVersion: v1
kind: Service
metadata:
  name: app-prueba # nombre de la imagen creada - docker images
  namespace: vidal
spec:
  type: NodePort      #30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30001       # Puerto que el Service expondrá
    targetPort: 9090  # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30001   # Puerto asignado en el nodo, opcional
  selector:
    app: app-prueba  # Debe coincidir con las etiquetas del Deployment